image: maven:3.8.5-eclipse-temurin-17-alpine

stages:
  - build

build server:
  stage: build
  script:
    - mvn install
  artifacts:
    paths:
      - target/backend-0.0.1-SNAPSHOT.jar

store to s3:
  stage: store
  image:
    name: amazon/aws-cli:2.9.15
    entrypoint: [""]
  script:
    - echo "j" > test.txt
    - aws s3 cp test.txt s3://$AWS_S3_BUCKET/test.txt

cache:
  paths:
    - .m2/repository

