variables:
  # `showDateTime` will show the passed time in milliseconds. You need to specify `--batch-mode` to make this work.
  MAVEN_OPTS: >-
    -Dhttps.protocols=TLSv1.2
    -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository
    -Dorg.slf4j.simpleLogger.showDateTime=true
    -Djava.awt.headless=true
  
  APP_VERSION: $CI_PIPELINE_ID


image: maven:3.8.4-eclipse-temurin-11-alpine

stages:
  - build
  - deploy

build server:
  stage: build
  script:
    - mvn install
  artifacts:
    paths:
      - target/backend-0.0.1-SNAPSHOT.jar

deploy:
  stage: deploy
  image:
    name: amazon/aws-cli:2.9.15
    entrypoint: [""]
  script:
    - aws s3 cp target/backend-0.0.1-SNAPSHOT.jar s3://$AWS_S3_BUCKET/$APP_VERSION.jar
    - aws elasticbeanstalk create-application-version --application-name "$APP_NAME" --version-label "$APP_VERSION" --source-bundle S3Bucket=$AWS_S3_BUCKET,S3Key="$APP_VERSION.jar"
    - aws elasticbeanstalk update-environment --application-name "$APP_NAME" --environment-name "Naturalgoods-env-1" --version-label "$APP_VERSION"
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: never


cache:
  paths:
    - .m2/repository

