variables:
  # `showDateTime` will show the passed time in milliseconds. You need to specify `--batch-mode` to make this work.
  MAVEN_OPTS: >-
    -Dhttps.protocols=TLSv1.2
    -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository
    -Dorg.slf4j.simpleLogger.showDateTime=true
    -Djava.awt.headless=true

  # As of Maven 3.3.0 instead of this you MAY define these options in `.mvn/maven.config` so the same config is used
  # when running from the command line.
  # As of Maven 3.6.1, the use of `--no-tranfer-progress` (or `-ntp`) suppresses download and upload messages. The use
  # of the `Slf4jMavenTransferListener` is no longer necessary.
  # `installAtEnd` and `deployAtEnd` are only effective with recent version of the corresponding plugins.
  MAVEN_CLI_OPTS: >-
    --batch-mode
    --errors
    --fail-at-end
    --show-version
    --no-transfer-progress
    -DinstallAtEnd=true
    -DdeployAtEnd=true

  
  APP_VERSION: $CI_PIPELINE_ID


image: maven:3.8.5-eclipse-temurin-17-alpine

stages:
  - build
  - deploy

build server:
  stage: build
  script:
    - mvn install
  artifacts:
    paths:
      - target/backend-0.0.1-SNAPSHOT.jar

deploy:
  stage: deploy
  image:
    name: amazon/aws-cli:2.9.15
    entrypoint: [""]
  script:
    - aws s3 cp target/backend-0.0.1-SNAPSHOT.jar s3://$AWS_S3_BUCKET/backend-$APP_VERSION-SNAPSHOT.jar
    - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID_DEPLOY
    - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY_DEPLOY
    - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID_DEPLOY
    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY_DEPLOY
    - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID_DEPLOY AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY_DEPLOY aws elasticbeanstalk create-application-version --application-name "Natural Goods" --version-label "${APP_VERSION}" --source-bundle S3Bucket=$AWS_S3_BUCKET,S3Key="backend-${APP_VERSION}-SNAPSHOT.jar"
    - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID_DEPLOY AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY_DEPLOY aws elasticbeanstalk update-environment --application-name "Natural Goods" --environment-name "Naturalgoods-env" --version-label "${APP_VERSION}"


cache:
  paths:
    - .m2/repository

