image: maven:3.8.5-eclipse-temurin-17-alpine

stages:
  - build
  - store

build server:
  stage: build
  script:
    - mvn install
  artifacts:
    paths:
      - target/backend-0.0.1-SNAPSHOT.jar

store to s3:
  stage: store
  image:
    name: amazon/aws-cli:2.9.15
    entrypoint: [""]
  script:
    - aws s3 cp target/backend-0.0.1-SNAPSHOT.jar s3://$AWS_S3_BUCKET/backend-0.0.1-SNAPSHOT.jar

cache:
  paths:
    - .m2/repository

