server:
  port: 5000
spring:
  datasource:
    url: jdbc:postgresql://naturalgoods.cr5uqxzufnns.us-east-1.rds.amazonaws.com:3306/postgres
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgresPlusDialect
        show-sql: false
    hibernate:
      ddl-auto: none
    open-in-view: false
  hikari:
    data-source-class-name:
  driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    url: ${spring.datasource.url}
    locations: classpath:db
    baseline-on-migrate: true
    validate-on-migrate: false
    out-of-order: true
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}

jwtSecret: 3K4N6P7Q9SATBVDWEXGZH2J3M5N6P8R9SAUCVDWFYGZH3K4M5P7Q8RATBU
jwtExpirationMs: 9000000
jwtRefreshExpirationMs: 86400000