server:
  port: 5000
spring:
  datasource:
    url: jdbc:postgresql://naturalgoods.cr5uqxzufnns.us-east-1.rds.amazonaws.com:3306/postgres
    username: postgres
    password: postgres
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgresPlusDialect
          show-sql: false
      hibernate:
        ddl-auto: none
      open-in-view: false
    hikari:
      data-source-class-name:
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    url: ${spring.datasource.url}
    locations: classpath:db
    baseline-on-migrate: true
    validate-on-migrate: false
    out-of-order: true
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}


mail:
  username: alisher-zhakenov@mail.ru
  password: bYg9WmyT9Mm0rmZgEs4m

jwtSecret: DCB38ABF33FA35ADF189F3C1476E4E2B111D78664224DACDC845F82357
jwtExpirationMs: 2592000000
jwtRefreshExpirationMs: 86400000

